name: CI

on [push] # Pipeline is runned every time when new push.

jobs:
 sast_scan:
  name: Run Bandit Scan # a tool designed to find common security issues in Python code
  runs-on: ubuntu-latest

  steps: # what the tool is going to to
  - name: Checkout code
    uses: actions/checkout@v2

    - name: Set up Python # bandit is python packet so we need to install it
      uses: actions/setup-python@v2
      with:
         python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r . # . -> scan everything
      
